<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class KasnariansyahBlokASeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        \App\Models\Room::factory()->count(48)->sequence(
            //Rusun KAsnariansyah Blok A Lantai 1
            [   'custom_id' => 'IAA001', 
                'unit_numbers_custom_id' => 'IUN001', 
                'price_tags_custom_id' => 'IPT016',
                'statuses_custom_id' => 'IST002',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn_flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn_dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi_listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi_air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAA002', 
                'unit_numbers_custom_id' => 'IUN002', 
                'price_tags_custom_id' => 'IPT016',
                'statuses_custom_id' => 'IST002',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn_flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn_dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi_listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi_air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAA003', 
                'unit_numbers_custom_id' => 'IUN003', 
                'price_tags_custom_id' => 'IPT016',
                'statuses_custom_id' => 'IST002',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn_flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn_dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi_listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi_air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAA004', 
                'unit_numbers_custom_id' => 'IUN004', 
                'price_tags_custom_id' => 'IPT016',
                'statuses_custom_id' => 'IST002',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn_flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn_dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi_listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi_air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAA005', 
                'unit_numbers_custom_id' => 'IUN005', 
                'price_tags_custom_id' => 'IPT016',
                'statuses_custom_id' => 'IST002',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn_flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn_dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi_listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi_air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAA006', 
                'unit_numbers_custom_id' => 'IUN006', 
                'price_tags_custom_id' => 'IPT016',
                'statuses_custom_id' => 'IST002',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn_flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn_dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi_listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi_air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAA007', 
                'unit_numbers_custom_id' => 'IUN007', 
                'price_tags_custom_id' => 'IPT016',
                'statuses_custom_id' => 'IST002',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn_flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn_dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi_listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi_air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAA008', 
                'unit_numbers_custom_id' => 'IUN008', 
                'price_tags_custom_id' => 'IPT016',
                'statuses_custom_id' => 'IST002',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn_flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn_dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi_listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi_air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAA009', 
                'unit_numbers_custom_id' => 'IUN009', 
                'price_tags_custom_id' => 'IPT016',
                'statuses_custom_id' => 'IST001',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn_flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn_dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi_listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi_air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAA010', 
                'unit_numbers_custom_id' => 'IUN010', 
                'price_tags_custom_id' => 'IPT016',
                'statuses_custom_id' => 'IST002',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn_flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn_dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi_listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi_air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAA011', 
                'unit_numbers_custom_id' => 'IUN011', 
                'price_tags_custom_id' => 'IPT016',
                'statuses_custom_id' => 'IST001',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn_flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn_dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi_listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi_air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAA012', 
                'unit_numbers_custom_id' => 'IUN012', 
                'price_tags_custom_id' => 'IPT016',
                'statuses_custom_id' => 'IST002',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn_flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn_dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi_listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi_air_custom_id' => 'IDR029'
            ],

            // Rusun Kasnariansyah Blok A Lantai 2
            [   'custom_id' => 'IAA013', 
                'unit_numbers_custom_id' => 'IUN001', 
                'price_tags_custom_id' => 'IPT017',
                'statuses_custom_id' => 'IST002',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn_flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn_dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi_listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi_air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAA014', 
                'unit_numbers_custom_id' => 'IUN002', 
                'price_tags_custom_id' => 'IPT017',
                'statuses_custom_id' => 'IST002',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn_flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn_dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi_listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi_air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAA015', 
                'unit_numbers_custom_id' => 'IUN003', 
                'price_tags_custom_id' => 'IPT017',
                'statuses_custom_id' => 'IST001',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn_flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn_dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi_listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi_air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAA016', 
                'unit_numbers_custom_id' => 'IUN004', 
                'price_tags_custom_id' => 'IPT017',
                'statuses_custom_id' => 'IST002',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn_flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn_dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi_listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi_air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAA017', 
                'unit_numbers_custom_id' => 'IUN005', 
                'price_tags_custom_id' => 'IPT017',
                'statuses_custom_id' => 'IST002',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn_flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn_dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi_listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi_air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAA018', 
                'unit_numbers_custom_id' => 'IUN006', 
                'price_tags_custom_id' => 'IPT017',
                'statuses_custom_id' => 'IST002',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn_flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn_dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi_listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi_air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAA019', 
                'unit_numbers_custom_id' => 'IUN007', 
                'price_tags_custom_id' => 'IPT017',
                'statuses_custom_id' => 'IST002',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn_flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn_dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi_listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi_air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAA020', 
                'unit_numbers_custom_id' => 'IUN008', 
                'price_tags_custom_id' => 'IPT017',
                'statuses_custom_id' => 'IST002',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn_flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn_dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi_listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi_air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAA021', 
                'unit_numbers_custom_id' => 'IUN009', 
                'price_tags_custom_id' => 'IPT017',
                'statuses_custom_id' => 'IST002',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn_flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn_dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi_listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi_air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAA022', 
                'unit_numbers_custom_id' => 'IUN010', 
                'price_tags_custom_id' => 'IPT017',
                'statuses_custom_id' => 'IST002',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn_flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn_dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi_listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi_air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAA023', 
                'unit_numbers_custom_id' => 'IUN011', 
                'price_tags_custom_id' => 'IPT017',
                'statuses_custom_id' => 'IST001',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn_flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn_dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi_listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi_air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAA024', 
                'unit_numbers_custom_id' => 'IUN012', 
                'price_tags_custom_id' => 'IPT017',
                'statuses_custom_id' => 'IST002',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn_flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn_dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi_listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi_air_custom_id' => 'IDR029'
            ],

            // Rusun Kasnariansyah Blok A Lantai 3
            [   'custom_id' => 'IAA025', 
                'unit_numbers_custom_id' => 'IUN001', 
                'price_tags_custom_id' => 'IPT018',
                'statuses_custom_id' => 'IST001',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn_flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn_dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi_listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi_air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAA026', 
                'unit_numbers_custom_id' => 'IUN002', 
                'price_tags_custom_id' => 'IPT018',
                'statuses_custom_id' => 'IST001',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn_flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn_dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi_listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi_air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAA027', 
                'unit_numbers_custom_id' => 'IUN003', 
                'price_tags_custom_id' => 'IPT018',
                'statuses_custom_id' => 'IST002',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn_flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn_dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi_listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi_air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAA028', 
                'unit_numbers_custom_id' => 'IUN004', 
                'price_tags_custom_id' => 'IPT018',
                'statuses_custom_id' => 'IST002',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn_flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn_dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi_listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi_air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAA029', 
                'unit_numbers_custom_id' => 'IUN005', 
                'price_tags_custom_id' => 'IPT018',
                'statuses_custom_id' => 'IST001',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn_flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn_dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi_listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi_air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAA030', 
                'unit_numbers_custom_id' => 'IUN006', 
                'price_tags_custom_id' => 'IPT018',
                'statuses_custom_id' => 'IST001',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn_flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn_dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi_listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi_air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAA031', 
                'unit_numbers_custom_id' => 'IUN007', 
                'price_tags_custom_id' => 'IPT018',
                'statuses_custom_id' => 'IST002',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn_flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn_dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi_listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi_air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAA032', 
                'unit_numbers_custom_id' => 'IUN008', 
                'price_tags_custom_id' => 'IPT018',
                'statuses_custom_id' => 'IST001',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn_flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn_dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi_listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi_air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAA033', 
                'unit_numbers_custom_id' => 'IUN009', 
                'price_tags_custom_id' => 'IPT018',
                'statuses_custom_id' => 'IST001',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn_flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn_dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi_listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi_air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAA034', 
                'unit_numbers_custom_id' => 'IUN010', 
                'price_tags_custom_id' => 'IPT018',
                'statuses_custom_id' => 'IST002',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn_flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn_dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi_listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi_air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAA035', 
                'unit_numbers_custom_id' => 'IUN011', 
                'price_tags_custom_id' => 'IPT018',
                'statuses_custom_id' => 'IST002',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn_flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn_dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi_listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi_air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAA036', 
                'unit_numbers_custom_id' => 'IUN012', 
                'price_tags_custom_id' => 'IPT018',
                'statuses_custom_id' => 'IST002',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn_flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn_dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi_listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi_air_custom_id' => 'IDR029'
            ],

            // Rusun KAsnariansyah Blok A Lantai 4
            [   'custom_id' => 'IAA037', 
                'unit_numbers_custom_id' => 'IUN001', 
                'price_tags_custom_id' => 'IPT019',
                'statuses_custom_id' => 'IST001',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn_flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn_dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi_listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi_air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAA038', 
                'unit_numbers_custom_id' => 'IUN002', 
                'price_tags_custom_id' => 'IPT019',
                'statuses_custom_id' => 'IST002',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn_flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn_dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi_listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi_air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAA039', 
                'unit_numbers_custom_id' => 'IUN003', 
                'price_tags_custom_id' => 'IPT019',
                'statuses_custom_id' => 'IST002',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn_flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn_dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi_listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi_air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAA040', 
                'unit_numbers_custom_id' => 'IUN004', 
                'price_tags_custom_id' => 'IPT019',
                'statuses_custom_id' => 'IST002',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn_flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn_dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi_listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi_air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAA041', 
                'unit_numbers_custom_id' => 'IUN005', 
                'price_tags_custom_id' => 'IPT019',
                'statuses_custom_id' => 'IST002',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn_flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn_dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi_listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi_air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAA042', 
                'unit_numbers_custom_id' => 'IUN006', 
                'price_tags_custom_id' => 'IPT019',
                'statuses_custom_id' => 'IST002',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn_flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn_dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi_listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi_air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAA043', 
                'unit_numbers_custom_id' => 'IUN007', 
                'price_tags_custom_id' => 'IPT019',
                'statuses_custom_id' => 'IST002',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn_flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn_dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi_listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi_air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAA044', 
                'unit_numbers_custom_id' => 'IUN008', 
                'price_tags_custom_id' => 'IPT019',
                'statuses_custom_id' => 'IST001',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn_flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn_dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi_listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi_air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAA045', 
                'unit_numbers_custom_id' => 'IUN009', 
                'price_tags_custom_id' => 'IPT019',
                'statuses_custom_id' => 'IST002',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn_flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn_dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi_listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi_air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAA046', 
                'unit_numbers_custom_id' => 'IUN010', 
                'price_tags_custom_id' => 'IPT019',
                'statuses_custom_id' => 'IST002',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn_flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn_dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi_listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi_air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAA047', 
                'unit_numbers_custom_id' => 'IUN011', 
                'price_tags_custom_id' => 'IPT019',
                'statuses_custom_id' => 'IST002',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn_flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn_dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi_listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi_air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAA048', 
                'unit_numbers_custom_id' => 'IUN012', 
                'price_tags_custom_id' => 'IPT019',
                'statuses_custom_id' => 'IST002',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn_flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn_dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi_listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi_air_custom_id' => 'IDR029'
            ],
            )->create();
    }
}
