<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class KasnariansyahBlokBSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        \App\Models\Room::factory()->count(60)->sequence(
            //Rusun Kasnariansyah Blok B Lantai Dasar
            [   'custom_id' => 'IAB001', 
                'unit_numbers_custom_id' => 'IUN001', 
                'price_tags_custom_id' => 'IPT020',
                'statuses_custom_id' => 'IST002',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn-flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn-dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi-listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi-air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAB002', 
                'unit_numbers_custom_id' => 'IUN002', 
                'price_tags_custom_id' => 'IPT020',
                'statuses_custom_id' => 'IST002',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn-flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn-dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi-listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi-air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAB003', 
                'unit_numbers_custom_id' => 'IUN003', 
                'price_tags_custom_id' => 'IPT020',
                'statuses_custom_id' => 'IST002',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn-flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn-dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi-listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi-air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAB004', 
                'unit_numbers_custom_id' => 'IUN004', 
                'price_tags_custom_id' => 'IPT020',
                'statuses_custom_id' => 'IST002',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn-flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn-dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi-listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi-air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAB005', 
                'unit_numbers_custom_id' => 'IUN005', 
                'price_tags_custom_id' => 'IPT020',
                'statuses_custom_id' => 'IST002',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn-flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn-dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi-listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi-air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAB006', 
                'unit_numbers_custom_id' => 'IUN006', 
                'price_tags_custom_id' => 'IPT020',
                'statuses_custom_id' => 'IST002',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn-flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn-dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi-listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi-air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAB007', 
                'unit_numbers_custom_id' => 'IUN007', 
                'price_tags_custom_id' => 'IPT020',
                'statuses_custom_id' => 'IST001',
               'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn-flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn-dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi-listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi-air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAB008', 
                'unit_numbers_custom_id' => 'IUN008', 
                'price_tags_custom_id' => 'IPT020',
                'statuses_custom_id' => 'IST002',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn-flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn-dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi-listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi-air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAB009', 
                'unit_numbers_custom_id' => 'IUN009', 
                'price_tags_custom_id' => 'IPT020',
                'statuses_custom_id' => 'IST002',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn-flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn-dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi-listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi-air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAB010', 
                'unit_numbers_custom_id' => 'IUN010', 
                'price_tags_custom_id' => 'IPT020',
                'statuses_custom_id' => 'IST002',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn-flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn-dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi-listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi-air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAB011', 
                'unit_numbers_custom_id' => 'IUN011', 
                'price_tags_custom_id' => 'IPT020',
                'statuses_custom_id' => 'IST001',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn-flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn-dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi-listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi-air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAB012', 
                'unit_numbers_custom_id' => 'IUN012', 
                'price_tags_custom_id' => 'IPT020',
                'statuses_custom_id' => 'IST001',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn-flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn-dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi-listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi-air_custom_id' => 'IDR029'
            ],

            // Rusun Kasnariansyah Blok B Lantai 1
            [   'custom_id' => 'IAB013', 
                'unit_numbers_custom_id' => 'IUN001', 
                'price_tags_custom_id' => 'IPT021',
                'statuses_custom_id' => 'IST002',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn-flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn-dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi-listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi-air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAB014', 
                'unit_numbers_custom_id' => 'IUN002', 
                'price_tags_custom_id' => 'IPT021',
                'statuses_custom_id' => 'IST001',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn-flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn-dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi-listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi-air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAB015', 
                'unit_numbers_custom_id' => 'IUN003', 
                'price_tags_custom_id' => 'IPT021',
                'statuses_custom_id' => 'IST002',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn-flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn-dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi-listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi-air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAB016', 
                'unit_numbers_custom_id' => 'IUN004', 
                'price_tags_custom_id' => 'IPT021',
                'statuses_custom_id' => 'IST002',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn-flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn-dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi-listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi-air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAB017', 
                'unit_numbers_custom_id' => 'IUN005', 
                'price_tags_custom_id' => 'IPT021',
                'statuses_custom_id' => 'IST001',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn-flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn-dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi-listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi-air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAB018', 
                'unit_numbers_custom_id' => 'IUN006', 
                'price_tags_custom_id' => 'IPT021',
                'statuses_custom_id' => 'IST001',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn-flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn-dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi-listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi-air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAB019', 
                'unit_numbers_custom_id' => 'IUN007', 
                'price_tags_custom_id' => 'IPT021',
                'statuses_custom_id' => 'IST001',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn-flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn-dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi-listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi-air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAB020', 
                'unit_numbers_custom_id' => 'IUN008', 
                'price_tags_custom_id' => 'IPT021',
                'statuses_custom_id' => 'IST002',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn-flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn-dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi-listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi-air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAB021', 
                'unit_numbers_custom_id' => 'IUN009', 
                'price_tags_custom_id' => 'IPT021',
                'statuses_custom_id' => 'IST001',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn-flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn-dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi-listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi-air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAB022', 
                'unit_numbers_custom_id' => 'IUN010', 
                'price_tags_custom_id' => 'IPT021',
                'statuses_custom_id' => 'IST001',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn-flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn-dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi-listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi-air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAB023', 
                'unit_numbers_custom_id' => 'IUN011', 
                'price_tags_custom_id' => 'IPT021',
                'statuses_custom_id' => 'IST002',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn-flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn-dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi-listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi-air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAB024', 
                'unit_numbers_custom_id' => 'IUN012', 
                'price_tags_custom_id' => 'IPT021',
                'statuses_custom_id' => 'IST001',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn-flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn-dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi-listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi-air_custom_id' => 'IDR029'
            ],
            // Rusun Kasnariansyah Blok B Lantai 2
            [   'custom_id' => 'IAB025', 
                'unit_numbers_custom_id' => 'IUN001', 
                'price_tags_custom_id' => 'IPT022',
                'statuses_custom_id' => 'IST002',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn-flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn-dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi-listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi-air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAB026', 
                'unit_numbers_custom_id' => 'IUN002', 
                'price_tags_custom_id' => 'IPT022',
                'statuses_custom_id' => 'IST001',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn-flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn-dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi-listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi-air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAB027', 
                'unit_numbers_custom_id' => 'IUN003', 
                'price_tags_custom_id' => 'IPT022',
                'statuses_custom_id' => 'IST001',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn-flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn-dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi-listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi-air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAB028', 
                'unit_numbers_custom_id' => 'IUN004', 
                'price_tags_custom_id' => 'IPT022',
                'statuses_custom_id' => 'IST002',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn-flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn-dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi-listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi-air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAB029', 
                'unit_numbers_custom_id' => 'IUN005', 
                'price_tags_custom_id' => 'IPT022',
                'statuses_custom_id' => 'IST001',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn-flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn-dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi-listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi-air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAB030', 
                'unit_numbers_custom_id' => 'IUN006', 
                'price_tags_custom_id' => 'IPT022',
                'statuses_custom_id' => 'IST001',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn-flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn-dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi-listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi-air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAB031', 
                'unit_numbers_custom_id' => 'IUN007', 
                'price_tags_custom_id' => 'IPT022',
                'statuses_custom_id' => 'IST001',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn-flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn-dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi-listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi-air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAB032', 
                'unit_numbers_custom_id' => 'IUN008', 
                'price_tags_custom_id' => 'IPT022',
                'statuses_custom_id' => 'IST002',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn-flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn-dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi-listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi-air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAB033', 
                'unit_numbers_custom_id' => 'IUN009', 
                'price_tags_custom_id' => 'IPT022',
                'statuses_custom_id' => 'IST002',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn-flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn-dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi-listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi-air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAB034', 
                'unit_numbers_custom_id' => 'IUN010', 
                'price_tags_custom_id' => 'IPT022',
                'statuses_custom_id' => 'IST002',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn-flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn-dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi-listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi-air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAB035', 
                'unit_numbers_custom_id' => 'IUN011', 
                'price_tags_custom_id' => 'IPT022',
                'statuses_custom_id' => 'IST001',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn-flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn-dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi-listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi-air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAB036', 
                'unit_numbers_custom_id' => 'IUN012', 
                'price_tags_custom_id' => 'IPT022',
                'statuses_custom_id' => 'IST001',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn-flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn-dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi-listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi-air_custom_id' => 'IDR029'
            ],
            // Rusun KAsnariansyah blok B lantai 3
            [   'custom_id' => 'IAB037', 
                'unit_numbers_custom_id' => 'IUN001', 
                'price_tags_custom_id' => 'IPT023',
                'statuses_custom_id' => 'IST001',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn-flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn-dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi-listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi-air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAB038', 
                'unit_numbers_custom_id' => 'IUN002', 
                'price_tags_custom_id' => 'IPT023',
                'statuses_custom_id' => 'IST002',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn-flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn-dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi-listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi-air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAB039', 
                'unit_numbers_custom_id' => 'IUN003', 
                'price_tags_custom_id' => 'IPT023',
                'statuses_custom_id' => 'IST002',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn-flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn-dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi-listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi-air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAB040', 
                'unit_numbers_custom_id' => 'IUN004', 
                'price_tags_custom_id' => 'IPT023',
                'statuses_custom_id' => 'IST002',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn-flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn-dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi-listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi-air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAB041', 
                'unit_numbers_custom_id' => 'IUN005', 
                'price_tags_custom_id' => 'IPT023',
                'statuses_custom_id' => 'IST002',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn-flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn-dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi-listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi-air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAB042', 
                'unit_numbers_custom_id' => 'IUN006', 
                'price_tags_custom_id' => 'IPT023',
                'statuses_custom_id' => 'IST002',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn-flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn-dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi-listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi-air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAB043', 
                'unit_numbers_custom_id' => 'IUN007', 
                'price_tags_custom_id' => 'IPT023',
                'statuses_custom_id' => 'IST001',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn-flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn-dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi-listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi-air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAB044', 
                'unit_numbers_custom_id' => 'IUN008', 
                'price_tags_custom_id' => 'IPT023',
                'statuses_custom_id' => 'IST001',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn-flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn-dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi-listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi-air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAB045', 
                'unit_numbers_custom_id' => 'IUN009', 
                'price_tags_custom_id' => 'IPT023',
                'statuses_custom_id' => 'IST002',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn-flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn-dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi-listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi-air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAB046', 
                'unit_numbers_custom_id' => 'IUN010', 
                'price_tags_custom_id' => 'IPT023',
                'statuses_custom_id' => 'IST001',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn-flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn-dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi-listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi-air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAB047', 
                'unit_numbers_custom_id' => 'IUN011', 
                'price_tags_custom_id' => 'IPT023',
                'statuses_custom_id' => 'IST002',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn-flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn-dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi-listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi-air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAB048', 
                'unit_numbers_custom_id' => 'IUN012', 
                'price_tags_custom_id' => 'IPT023',
                'statuses_custom_id' => 'IST002',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn-flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn-dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi-listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi-air_custom_id' => 'IDR029'
            ],
            // Rusun Kasnariansyah Blok B Lantai 4
            [   'custom_id' => 'IAB049', 
                'unit_numbers_custom_id' => 'IUN001', 
                'price_tags_custom_id' => 'IPT024',
                'statuses_custom_id' => 'IST001',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn-flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn-dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi-listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi-air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAB050', 
                'unit_numbers_custom_id' => 'IUN002', 
                'price_tags_custom_id' => 'IPT024',
                'statuses_custom_id' => 'IST001',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn-flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn-dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi-listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi-air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAB051', 
                'unit_numbers_custom_id' => 'IUN003', 
                'price_tags_custom_id' => 'IPT024',
                'statuses_custom_id' => 'IST001',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn-flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn-dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi-listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi-air_custom_id' => 'IDR029'
            ],    
            [   'custom_id' => 'IAB052', 
                'unit_numbers_custom_id' => 'IUN004', 
                'price_tags_custom_id' => 'IPT024',
                'statuses_custom_id' => 'IST002',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn-flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn-dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi-listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi-air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAB053', 
                'unit_numbers_custom_id' => 'IUN005', 
                'price_tags_custom_id' => 'IPT024',
                'statuses_custom_id' => 'IST001',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn-flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn-dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi-listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi-air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAB054', 
                'unit_numbers_custom_id' => 'IUN006', 
                'price_tags_custom_id' => 'IPT024',
                'statuses_custom_id' => 'IST001',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn-flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn-dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi-listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi-air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAB055', 
                'unit_numbers_custom_id' => 'IUN007', 
                'price_tags_custom_id' => 'IPT024',
                'statuses_custom_id' => 'IST001',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn-flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn-dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi-listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi-air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAB056', 
                'unit_numbers_custom_id' => 'IUN008', 
                'price_tags_custom_id' => 'IPT024',
                'statuses_custom_id' => 'IST001',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn-flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn-dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi-listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi-air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAB057', 
                'unit_numbers_custom_id' => 'IUN009', 
                'price_tags_custom_id' => 'IPT024',
                'statuses_custom_id' => 'IST001',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn-flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn-dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi-listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi-air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAB058', 
                'unit_numbers_custom_id' => 'IUN010', 
                'price_tags_custom_id' => 'IPT024',
                'statuses_custom_id' => 'IST002',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn-flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn-dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi-listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi-air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAB059', 
                'unit_numbers_custom_id' => 'IUN011', 
                'price_tags_custom_id' => 'IPT024',
                'statuses_custom_id' => 'IST001',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn-flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn-dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi-listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi-air_custom_id' => 'IDR029'
            ],
            [   'custom_id' => 'IAB060', 
                'unit_numbers_custom_id' => 'IUN012', 
                'price_tags_custom_id' => 'IPT024',
                'statuses_custom_id' => 'IST001',
                'damage_rooms_lantai_custom_id' => 'IDR001',
                'damage_rooms_kusen_custom_id' => 'IDR005',
                'damage_rooms_pintu_custom_id' => 'IDR009',
                'damage_rooms_jendela_custom_id' => 'IDR013',
                'damage_rooms_fn-flatfond_custom_id' => 'IDR017',
                'damage_rooms_fn-dinding_custom_id' => 'IDR021',
                'damage_rooms_instalasi-listrik_custom_id' => 'IDR025',
                'damage_rooms_instalasi-air_custom_id' => 'IDR029'
            ],
            )->create();
    }
}
