<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class RoomSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        \App\Models\Room::factory()->count(2)->sequence(
        //Rusun Kertapati Blok A Lantai Dasar
        [   'custom_id' => 'IRO001', 
            'unit_numbers_custom_id' => 'IUN001', 
            'price_tags_custom_id' => 'IPT001',
            'statuses_custom_id' => 'IST002',
            'damage_rooms_lantai_custom_id' => null,
            'damage_rooms_kusen_custom_id' => null,
            'damage_rooms_pintu_custom_id' => null,
            'damage_rooms_jendela_custom_id' => null,
            'damage_rooms_fn_flatfond_custom_id' => null,
            'damage_rooms_fn_dinding_custom_id' => null,
            'damage_rooms_instalasi_listrik_custom_id' => null,
            'damage_rooms_instalasi_air_custom_id' => null
        ],
        [   'custom_id' => 'IRO002', 
            'unit_numbers_custom_id' => 'IUN002', 
            'price_tags_custom_id' => 'IPT001',
            'statuses_custom_id' => 'IST002',
            'damage_rooms_lantai_custom_id' => null,
            'damage_rooms_kusen_custom_id' => null,
            'damage_rooms_pintu_custom_id' => null,
            'damage_rooms_jendela_custom_id' => null,
            'damage_rooms_fn_flatfond_custom_id' => null,
            'damage_rooms_fn_dinding_custom_id' => null,
            'damage_rooms_instalasi_listrik_custom_id' => null,
            'damage_rooms_instalasi_air_custom_id' => null
        ],
        // [   'custom_id' => 'IRO003', 
        //     'unit_numbers_custom_id' => 'IUN003', 
        //     'price_tags_custom_id' => 'IPT001',
        //     'statuses_custom_id' => 'IST002',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // //Rusun Kertapati Blok A Lantai 1
        // [   'custom_id' => 'IRO004', 
        //     'unit_numbers_custom_id' => 'IUN001', 
        //     'price_tags_custom_id' => 'IPT002',
        //     'statuses_custom_id' => 'IST002',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO005', 
        //     'unit_numbers_custom_id' => 'IUN002', 
        //     'price_tags_custom_id' => 'IPT002',
        //     'statuses_custom_id' => 'IST002',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO006', 
        //     'unit_numbers_custom_id' => 'IUN003', 
        //     'price_tags_custom_id' => 'IPT002',
        //     'statuses_custom_id' => 'IST002',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO007', 
        //     'unit_numbers_custom_id' => 'IUN004', 
        //     'price_tags_custom_id' => 'IPT002',
        //     'statuses_custom_id' => 'IST001',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO008', 
        //     'unit_numbers_custom_id' => 'IUN005', 
        //     'price_tags_custom_id' => 'IPT002',
        //     'statuses_custom_id' => 'IST002',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO009', 
        //     'unit_numbers_custom_id' => 'IUN006', 
        //     'price_tags_custom_id' => 'IPT002',
        //     'statuses_custom_id' => 'IST002',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO010', 
        //     'unit_numbers_custom_id' => 'IUN007', 
        //     'price_tags_custom_id' => 'IPT002',
        //     'statuses_custom_id' => 'IST002',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO011', 
        //     'unit_numbers_custom_id' => 'IUN008', 
        //     'price_tags_custom_id' => 'IPT002',
        //     'statuses_custom_id' => 'IST001',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO012', 
        //     'unit_numbers_custom_id' => 'IUN009', 
        //     'price_tags_custom_id' => 'IPT002',
        //     'statuses_custom_id' => 'IST001',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO013', 
        //     'unit_numbers_custom_id' => 'IUN010', 
        //     'price_tags_custom_id' => 'IPT002',
        //     'statuses_custom_id' => 'IST002',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO014', 
        //     'unit_numbers_custom_id' => 'IUN011', 
        //     'price_tags_custom_id' => 'IPT002',
        //     'statuses_custom_id' => 'IST001',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO015', 
        //     'unit_numbers_custom_id' => 'IUN012', 
        //     'price_tags_custom_id' => 'IPT002',
        //     'statuses_custom_id' => 'IST002',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO016', 
        //     'unit_numbers_custom_id' => 'IUN013', 
        //     'price_tags_custom_id' => 'IPT002',
        //     'statuses_custom_id' => 'IST002',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO017', 
        //     'unit_numbers_custom_id' => 'IUN014', 
        //     'price_tags_custom_id' => 'IPT002',
        //     'statuses_custom_id' => 'IST001',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO018', 
        //     'unit_numbers_custom_id' => 'IUN015', 
        //     'price_tags_custom_id' => 'IPT002',
        //     'statuses_custom_id' => 'IST001',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO019', 
        //     'unit_numbers_custom_id' => 'IUN016', 
        //     'price_tags_custom_id' => 'IPT002',
        //     'statuses_custom_id' => 'IST001',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO020', 
        //     'unit_numbers_custom_id' => 'IUN017', 
        //     'price_tags_custom_id' => 'IPT002',
        //     'statuses_custom_id' => 'IST002',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO021', 
        //     'unit_numbers_custom_id' => 'IUN018', 
        //     'price_tags_custom_id' => 'IPT002',
        //     'statuses_custom_id' => 'IST001',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO022', 
        //     'unit_numbers_custom_id' => 'IUN019', 
        //     'price_tags_custom_id' => 'IPT002',
        //     'statuses_custom_id' => 'IST001',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO023', 
        //     'unit_numbers_custom_id' => 'IUN020', 
        //     'price_tags_custom_id' => 'IPT002',
        //     'statuses_custom_id' => 'IST002',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO024', 
        //     'unit_numbers_custom_id' => 'IUN021', 
        //     'price_tags_custom_id' => 'IPT002',
        //     'statuses_custom_id' => 'IST001',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO025', 
        //     'unit_numbers_custom_id' => 'IUN022', 
        //     'price_tags_custom_id' => 'IPT002',
        //     'statuses_custom_id' => 'IST002',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO026', 
        //     'unit_numbers_custom_id' => 'IUN023', 
        //     'price_tags_custom_id' => 'IPT002',
        //     'statuses_custom_id' => 'IST001',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO027', 
        //     'unit_numbers_custom_id' => 'IUN024', 
        //     'price_tags_custom_id' => 'IPT002',
        //     'statuses_custom_id' => 'IST001',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],

        // // Rusun Kertapati Blok A Lantai 2
        // [   'custom_id' => 'IRO028', 
        //     'unit_numbers_custom_id' => 'IUN001', 
        //     'price_tags_custom_id' => 'IPT003',
        //     'statuses_custom_id' => 'IST002',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO029', 
        //     'unit_numbers_custom_id' => 'IUN002', 
        //     'price_tags_custom_id' => 'IPT003',
        //     'statuses_custom_id' => 'IST001',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO030', 
        //     'unit_numbers_custom_id' => 'IUN003', 
        //     'price_tags_custom_id' => 'IPT003',
        //     'statuses_custom_id' => 'IST001',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO031', 
        //     'unit_numbers_custom_id' => 'IUN004', 
        //     'price_tags_custom_id' => 'IPT003',
        //     'statuses_custom_id' => 'IST001',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO032', 
        //     'unit_numbers_custom_id' => 'IUN005', 
        //     'price_tags_custom_id' => 'IPT003',
        //     'statuses_custom_id' => 'IST002',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO033', 
        //     'unit_numbers_custom_id' => 'IUN006', 
        //     'price_tags_custom_id' => 'IPT003',
        //     'statuses_custom_id' => 'IST002',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO034', 
        //     'unit_numbers_custom_id' => 'IUN007', 
        //     'price_tags_custom_id' => 'IPT003',
        //     'statuses_custom_id' => 'IST002',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO035', 
        //     'unit_numbers_custom_id' => 'IUN008', 
        //     'price_tags_custom_id' => 'IPT003',
        //     'statuses_custom_id' => 'IST001',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO036', 
        //     'unit_numbers_custom_id' => 'IUN009', 
        //     'price_tags_custom_id' => 'IPT003',
        //     'statuses_custom_id' => 'IST001',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO037', 
        //     'unit_numbers_custom_id' => 'IUN010', 
        //     'price_tags_custom_id' => 'IPT003',
        //     'statuses_custom_id' => 'IST001',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO038', 
        //     'unit_numbers_custom_id' => 'IUN011', 
        //     'price_tags_custom_id' => 'IPT003',
        //     'statuses_custom_id' => 'IST002',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO039', 
        //     'unit_numbers_custom_id' => 'IUN012', 
        //     'price_tags_custom_id' => 'IPT003',
        //     'statuses_custom_id' => 'IST002',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO040', 
        //     'unit_numbers_custom_id' => 'IUN013', 
        //     'price_tags_custom_id' => 'IPT003',
        //     'statuses_custom_id' => 'IST002',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO041', 
        //     'unit_numbers_custom_id' => 'IUN014', 
        //     'price_tags_custom_id' => 'IPT003',
        //     'statuses_custom_id' => 'IST002',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO042', 
        //     'unit_numbers_custom_id' => 'IUN015', 
        //     'price_tags_custom_id' => 'IPT003',
        //     'statuses_custom_id' => 'IST002',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO043', 
        //     'unit_numbers_custom_id' => 'IUN016', 
        //     'price_tags_custom_id' => 'IPT003',
        //     'statuses_custom_id' => 'IST001',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO044', 
        //     'unit_numbers_custom_id' => 'IUN017', 
        //     'price_tags_custom_id' => 'IPT003',
        //     'statuses_custom_id' => 'IST001',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO045', 
        //     'unit_numbers_custom_id' => 'IUN018', 
        //     'price_tags_custom_id' => 'IPT003',
        //     'statuses_custom_id' => 'IST002',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO046', 
        //     'unit_numbers_custom_id' => 'IUN019', 
        //     'price_tags_custom_id' => 'IPT003',
        //     'statuses_custom_id' => 'IST001',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO047', 
        //     'unit_numbers_custom_id' => 'IUN020', 
        //     'price_tags_custom_id' => 'IPT003',
        //     'statuses_custom_id' => 'IST002',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO048', 
        //     'unit_numbers_custom_id' => 'IUN021', 
        //     'price_tags_custom_id' => 'IPT003',
        //     'statuses_custom_id' => 'IST002',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO049', 
        //     'unit_numbers_custom_id' => 'IUN022', 
        //     'price_tags_custom_id' => 'IPT003',
        //     'statuses_custom_id' => 'IST001',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO050', 
        //     'unit_numbers_custom_id' => 'IUN023', 
        //     'price_tags_custom_id' => 'IPT003',
        //     'statuses_custom_id' => 'IST001',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO051', 
        //     'unit_numbers_custom_id' => 'IUN024', 
        //     'price_tags_custom_id' => 'IPT003',
        //     'statuses_custom_id' => 'IST001',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],

        // // Rusun Kertapati Blok A Lantai 3
        // [   'custom_id' => 'IRO052', 
        //     'unit_numbers_custom_id' => 'IUN001', 
        //     'price_tags_custom_id' => 'IPT004',
        //     'statuses_custom_id' => 'IST002',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO053', 
        //     'unit_numbers_custom_id' => 'IUN002', 
        //     'price_tags_custom_id' => 'IPT004',
        //     'statuses_custom_id' => 'IST001',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO054', 
        //     'unit_numbers_custom_id' => 'IUN003', 
        //     'price_tags_custom_id' => 'IPT004',
        //     'statuses_custom_id' => 'IST001',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO055', 
        //     'unit_numbers_custom_id' => 'IUN004', 
        //     'price_tags_custom_id' => 'IPT004',
        //     'statuses_custom_id' => 'IST001',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO056', 
        //     'unit_numbers_custom_id' => 'IUN005', 
        //     'price_tags_custom_id' => 'IPT004',
        //     'statuses_custom_id' => 'IST001',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO057', 
        //     'unit_numbers_custom_id' => 'IUN006', 
        //     'price_tags_custom_id' => 'IPT004',
        //     'statuses_custom_id' => 'IST001',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO058', 
        //     'unit_numbers_custom_id' => 'IUN007', 
        //     'price_tags_custom_id' => 'IPT004',
        //     'statuses_custom_id' => 'IST002',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO059', 
        //     'unit_numbers_custom_id' => 'IUN008', 
        //     'price_tags_custom_id' => 'IPT004',
        //     'statuses_custom_id' => 'IST001',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO060', 
        //     'unit_numbers_custom_id' => 'IUN009', 
        //     'price_tags_custom_id' => 'IPT004',
        //     'statuses_custom_id' => 'IST001',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO061', 
        //     'unit_numbers_custom_id' => 'IUN010', 
        //     'price_tags_custom_id' => 'IPT004',
        //     'statuses_custom_id' => 'IST001',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO062', 
        //     'unit_numbers_custom_id' => 'IUN011', 
        //     'price_tags_custom_id' => 'IPT004',
        //     'statuses_custom_id' => 'IST001',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO063', 
        //     'unit_numbers_custom_id' => 'IUN012', 
        //     'price_tags_custom_id' => 'IPT004',
        //     'statuses_custom_id' => 'IST001',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO064', 
        //     'unit_numbers_custom_id' => 'IUN013', 
        //     'price_tags_custom_id' => 'IPT004',
        //     'statuses_custom_id' => 'IST001',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO065', 
        //     'unit_numbers_custom_id' => 'IUN014', 
        //     'price_tags_custom_id' => 'IPT004',
        //     'statuses_custom_id' => 'IST002',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO066', 
        //     'unit_numbers_custom_id' => 'IUN015', 
        //     'price_tags_custom_id' => 'IPT004',
        //     'statuses_custom_id' => 'IST001',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO067', 
        //     'unit_numbers_custom_id' => 'IUN016', 
        //     'price_tags_custom_id' => 'IPT004',
        //     'statuses_custom_id' => 'IST001',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO068', 
        //     'unit_numbers_custom_id' => 'IUN017', 
        //     'price_tags_custom_id' => 'IPT004',
        //     'statuses_custom_id' => 'IST001',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO069', 
        //     'unit_numbers_custom_id' => 'IUN018', 
        //     'price_tags_custom_id' => 'IPT004',
        //     'statuses_custom_id' => 'IST002',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO070', 
        //     'unit_numbers_custom_id' => 'IUN019', 
        //     'price_tags_custom_id' => 'IPT004',
        //     'statuses_custom_id' => 'IST001',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO071', 
        //     'unit_numbers_custom_id' => 'IUN020', 
        //     'price_tags_custom_id' => 'IPT004',
        //     'statuses_custom_id' => 'IST001',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO072', 
        //     'unit_numbers_custom_id' => 'IUN021', 
        //     'price_tags_custom_id' => 'IPT004',
        //     'statuses_custom_id' => 'IST001',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO073', 
        //     'unit_numbers_custom_id' => 'IUN022', 
        //     'price_tags_custom_id' => 'IPT004',
        //     'statuses_custom_id' => 'IST001',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO074', 
        //     'unit_numbers_custom_id' => 'IUN023', 
        //     'price_tags_custom_id' => 'IPT004',
        //     'statuses_custom_id' => 'IST001',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO075', 
        //     'unit_numbers_custom_id' => 'IUN024', 
        //     'price_tags_custom_id' => 'IPT004',
        //     'statuses_custom_id' => 'IST001',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],

        // // Rusun Kertapati Blok A Lantai 4
        // [   'custom_id' => 'IRO076', 
        //     'unit_numbers_custom_id' => 'IUN001', 
        //     'price_tags_custom_id' => 'IPT005',
        //     'statuses_custom_id' => 'IST001',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO077', 
        //     'unit_numbers_custom_id' => 'IUN002', 
        //     'price_tags_custom_id' => 'IPT005',
        //     'statuses_custom_id' => 'IST002',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO078', 
        //     'unit_numbers_custom_id' => 'IUN003', 
        //     'price_tags_custom_id' => 'IPT005',
        //     'statuses_custom_id' => 'IST002',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO079', 
        //     'unit_numbers_custom_id' => 'IUN004', 
        //     'price_tags_custom_id' => 'IPT005',
        //     'statuses_custom_id' => 'IST002',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO080', 
        //     'unit_numbers_custom_id' => 'IUN005', 
        //     'price_tags_custom_id' => 'IPT005',
        //     'statuses_custom_id' => 'IST002',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO081', 
        //     'unit_numbers_custom_id' => 'IUN006', 
        //     'price_tags_custom_id' => 'IPT005',
        //     'statuses_custom_id' => 'IST002',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO082', 
        //     'unit_numbers_custom_id' => 'IUN007', 
        //     'price_tags_custom_id' => 'IPT005',
        //     'statuses_custom_id' => 'IST002',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO083', 
        //     'unit_numbers_custom_id' => 'IUN008', 
        //     'price_tags_custom_id' => 'IPT005',
        //     'statuses_custom_id' => 'IST001',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO084', 
        //     'unit_numbers_custom_id' => 'IUN009', 
        //     'price_tags_custom_id' => 'IPT005',
        //     'statuses_custom_id' => 'IST002',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO085', 
        //     'unit_numbers_custom_id' => 'IUN010', 
        //     'price_tags_custom_id' => 'IPT005',
        //     'statuses_custom_id' => 'IST002',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO086', 
        //     'unit_numbers_custom_id' => 'IUN011', 
        //     'price_tags_custom_id' => 'IPT005',
        //     'statuses_custom_id' => 'IST002',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO087', 
        //     'unit_numbers_custom_id' => 'IUN012', 
        //     'price_tags_custom_id' => 'IPT005',
        //     'statuses_custom_id' => 'IST002',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO088', 
        //     'unit_numbers_custom_id' => 'IUN013', 
        //     'price_tags_custom_id' => 'IPT005',
        //     'statuses_custom_id' => 'IST001',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO089', 
        //     'unit_numbers_custom_id' => 'IUN014', 
        //     'price_tags_custom_id' => 'IPT005',
        //     'statuses_custom_id' => 'IST001',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO090', 
        //     'unit_numbers_custom_id' => 'IUN015', 
        //     'price_tags_custom_id' => 'IPT005',
        //     'statuses_custom_id' => 'IST001',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO091', 
        //     'unit_numbers_custom_id' => 'IUN016', 
        //     'price_tags_custom_id' => 'IPT005',
        //     'statuses_custom_id' => 'IST002',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO092', 
        //     'unit_numbers_custom_id' => 'IUN017', 
        //     'price_tags_custom_id' => 'IPT005',
        //     'statuses_custom_id' => 'IST002',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO093', 
        //     'unit_numbers_custom_id' => 'IUN018', 
        //     'price_tags_custom_id' => 'IPT005',
        //     'statuses_custom_id' => 'IST002',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO095', 
        //     'unit_numbers_custom_id' => 'IUN019', 
        //     'price_tags_custom_id' => 'IPT005',
        //     'statuses_custom_id' => 'IST001',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO096', 
        //     'unit_numbers_custom_id' => 'IUN020', 
        //     'price_tags_custom_id' => 'IPT005',
        //     'statuses_custom_id' => 'IST001',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO097', 
        //     'unit_numbers_custom_id' => 'IUN021', 
        //     'price_tags_custom_id' => 'IPT005',
        //     'statuses_custom_id' => 'IST002',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO098', 
        //     'unit_numbers_custom_id' => 'IUN022', 
        //     'price_tags_custom_id' => 'IPT005',
        //     'statuses_custom_id' => 'IST002',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO099', 
        //     'unit_numbers_custom_id' => 'IUN023', 
        //     'price_tags_custom_id' => 'IPT005',
        //     'statuses_custom_id' => 'IST002',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        // [   'custom_id' => 'IRO100', 
        //     'unit_numbers_custom_id' => 'IUN024', 
        //     'price_tags_custom_id' => 'IPT005',
        //     'statuses_custom_id' => 'IST001',
        //     'damage_rooms_lantai_custom_id' => null,
        //     'damage_rooms_kusen_custom_id' => null,
        //     'damage_rooms_pintu_custom_id' => null,
        //     'damage_rooms_jendela_custom_id' => null,
        //     'damage_rooms_fn-flatfond_custom_id' => null,
        //     'damage_rooms_fn-dinding_custom_id' => null,
        //     'damage_rooms_instalasi-listrik_custom_id' => null,
        //     'damage_rooms_instalasi-air_custom_id' => null
        // ],
        
        // Rusun Kertapati Blok B Lantai Dasar
        // Rusun Kertapati Blok B Lantai 1
        // Rusun Kertapati Blok B Lantai 2
        // Rusun Kertapati Blok B Lantai 3
        // Rusun Kertapati Blok B Lantai 4
        // Rusun ....

        )->create();
    }
}
